### ISSUE TITLE
Unusable embeddings

### ISSUE THREAD

**Issue by Mahmedturk** [zenanz/ChemPatentEmbeddings#3] opened 2019-12-12 01:31 UTC
Hi,

Both of the embeddings given in this repo are unusable. The word2vec.bin cannot be converted to text.
And ELMo cannot be used, I get the following error while using it,.
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by zenanz** [comment] 2020-04-14 10:12
Duplicate of #1 . We've put them on server for public access.

**Closed as completed** 2020-05-26 10:53 UTC
